urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *

urlpatterns = patterns('karrie.django.source',
    url(r'^$', 
        'views.index', 
        name='source_index'),
        
    url(r'^package/(?P<slug>\w+)/',
        'views.package_details',
        name = 'source_package_details'),

    url(r'^modul/(?P<pk>\d+)$', 
        'views.mod_details',
        name ='source_modul_details'),
        
    url(r'^m/(?P<rep_slug>\w+)/(?P<name>\w+(?:\.\w+))$',
        'views.mod_named_details',
        name ='source_modul_named_details'),
 
    url(r'suche/$',
        'views.search',
        name = 'source_search'),
        
    url(r'^modultree/', 
        'views.modultree',
        name ='source_modultree'),
)

models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.contrib.gis.db import models
from django.contrib.auth.models import User, Group
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
import re
from django.core.validators import RegexValidator

filename_regex = re.compile(r'\w+(?:\.\w+)$')
filename_validator = RegexValidator(filename_regex, _(u'Bitte in der Form <Dateiname>.<Dateiendung>'), 'invalid')

class Package(models.Model):
    name = models.CharField(max_length = 120, help_text = u'Paketname')
    slug = models.SlugField(unique = True, help_text = u'Eindeutige, URL-konforme Bezeichnung (Kleinschreibung)')
    description = models.TextField(verbose_name=u'Beschreibung', null=True, blank=True, help_text = u'Beschreibung des Pakets in HTML')
    reps = models.ManyToManyField('Repository', related_name='repositories', verbose_name='Repositories', help_text = u'Verknüpfte Repositories.')
    
    class Meta:
        ordering = ['name']
        verbose_name = u'Paket'
        verbose_name_plural = u'Pakete'
    
    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('source_package_details', kwargs={'slug':self.slug})

class Repository(models.Model):
    name = models.CharField(max_length = 120, help_text = u'Name des Repositories')
    slug = models.SlugField(help_text = u'Eindeutige, URL-konforme Bezeichnung (Kleinschreibung)')
    last_modified = models.DateTimeField(auto_now = True)
    user = models.ForeignKey(User, help_text = u'Zuständiger Benutzer')
    
    class Meta:
        ordering = ['name']
        verbose_name = u'Repository'
        verbose_name_plural = u'Repositories'
    
    def __unicode__(self):
        return self.name
    
    def get_moduletree_url(self):
        return reverse('source_modultree') + '#rep-%s' % self.slug
    
    def get_absolute_url(self):
        return self.get_moduletree_url()
    
class CodeLanguage(models.Model):
    lang = models.CharField(max_length = 220, help_text = u'Programmier- / Skriptsprache, Dateityp')
    
    class Meta:
        ordering = ['lang']
        verbose_name = u'Quelltextsprache'
        verbose_name_plural = u'Quelltextsprachen'
    
    def __unicode__(self):
        return self.lang
    
class DataType(models.Model):
    type = models.CharField(max_length = 120, help_text = u'Name des Datentyps')
    
    class Meta:
        ordering = ['type']
        verbose_name = u'Datentyp'
        verbose_name_plural = u'Datentypen'
        
    def __unicode__(self):
        return self.type
    
class Parameter(models.Model):
    key = models.CharField(max_length = 120, verbose_name = u'Variable', help_text = u'Parametername / Variablenname')
    value = models.CharField(max_length = 120, verbose_name = u'Beschreibung', help_text = u'Beschreibung Parameter / Variable')
    datatype = models.ForeignKey(DataType, verbose_name = u'Datentyp')
    
    class Meta:
        ordering = ['key']
        verbose_name = u'Parameter'
        verbose_name_plural = u'Parameter'

    def get_admin_url(self):
        return reverse('admin:source_parameter_change', args=(self.id,))
        
    def __unicode__(self):
        return u'%s: %s (%s)' %(self.key, self.value, self.datatype)

class Modul(models.Model):
    name = models.CharField(max_length = 225, validators=[filename_validator], help_text = u'Dateiname, inklusive Dateiendung')
    last_modified = models.DateTimeField(help_text = u'Datum / Uhrzeit letzte Revision')
    repository = models.ForeignKey(Repository, help_text = u'Verknüpftes Repository')
    code = models.TextField(help_text = u'Der eigentlich Quellcode')
    input_params = models.ManyToManyField(Parameter, related_name='input_parameters', blank = True, null = True, help_text = u'Parameter, die/der benötigt werden, um dieses Modul aufzurufen')
    output_params = models.ManyToManyField(Parameter, related_name='output_parameters', blank = True, null = True, help_text = u'Parameter, die/der zurückgegeben wird')
    depencencys = models.ManyToManyField("self", symmetrical = False, blank = True, null = True, verbose_name = u'Abhängige Module')
    user = models.ForeignKey(User, help_text = u'Zuständiger Benutzer')
    revision = models.CharField(max_length = 10, default="1.0", help_text = u'Aktuelle Revision')
    code_description = models.TextField(verbose_name = u'Beschreibung Code', help_text = u'Beschreibung des dargestellten Codes')
    code_language = models.ForeignKey(CodeLanguage, verbose_name = u'Sprache', help_text = u'Sprache des Quelltextes')
        
    class Meta:
        ordering = ['name']
        unique_together = (('name', 'repository'),)
        verbose_name = u'Modul'
        verbose_name_plural = u'Module'
        
    def __unicode__(self):
        return self.name
    
    def __repr__(self):
        return '<b>%s</b> (<a href="%s">suchen</a>|<a href="%s">edit</a>)' %(self.name, self.get_admin_search_url(), self.get_admin_url())
    
    def get_admin_search_url(self):
        return reverse('admin:source_modul_changelist')+'?q=%s'%(self.name)
    
    def get_admin_url(self):
        return reverse('admin:source_modul_change', args=(self.id,))
    
    def get_called_by(self):
        return Modul.objects.filter(depencencys__in = [self])
    get_called_by.short_description = u'Wird aufgerufen von'
    get_called_by.allow_tags = True

    
    def get_calls(self):
        return self.depencencys.all()
    get_calls.short_description = u'Ruft auf'
    get_calls.allow_tags = True

    def get_parsed_descr(self):
        s = self.code_description
        braces = re.findall(r'\(.*?\)', s)
        for b in braces:
            clean = b[1:-1]
            try:
                p = Parameter.objects.get(key = clean)
            except:
                p = None
            if p:
                replace_text = u'(<a class="parameter" href="%s" title="%s">%s</a>)' %(p.get_admin_url(),p.value, p.key)
                s = s.replace(b, replace_text)
        return s
    get_parsed_descr.short_description = u'Beschreibung'
    get_parsed_descr.allow_tags = True

    def get_absolute_url(self):
        return reverse('source_modul_named_details', args = (self.repository.slug, self.name)) 
        #return reverse('source_modul_details', kwargs={'pk':self.pk})

templates/source/html/base.html
{% extends 'base.html' %}
<html>
	<head>
		<title>{% block page_title %}{% block title %}{% endblock %} | SOURCE{% endblock %}</title>
		{% block css %}
			{{ block.super }}
			<link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}source/style.css" />
			<link rel="stylesheet" type="text/css" media="print" href="{{ STATIC_URL }}source/print.css" />
		{% endblock %}
	</head>
	<body>
		{% block navi %}
		
		<ul>
			<li><a href="{% url karrie.django.source.views.index %}">Source-Home</a></li>
			<li><a href="{% url karrie.django.source.views.modultree %}">Modul-Baum</a></li>
		</ul>
		{% endblock %}
		{% block main_content %}
		<!--[if IE]>
		<ul class="error"><li><p>Lieber Besucher, liebe Besucherin,</p><p>Sie verwenden den Internet Explorer. Zur optimalen Darstellugen des Inhalts empfiehlt <a href="http://g2007.ch/">g2007.ch</a> den <a href="http://www.mozilla-europe.org/de/firefox/">Mozilla Firefox Browser</a>.</p></li></ul><br />
		<![endif]-->
			<div class="box">
			{% block content %}
			{% endblock %} 
			</div>
		{% endblock %}
		
		{% block sub_content %}
			<h2>Suche</h2>
			<p><small>Suche in Modulen (Beschreibung, Parameter, Quelltext), Paketen, Quelltextsprache, Repository.</small></p>
			<form action="{% url source_search %}" method="post">
				<table border="0">
				{% csrf_token %} <!-- left: csrf_token -->
				{{ search_form.as_table }}
				<p><input name="post" class="submit-post" value="Abschicken" type="submit" /></p>
				</table>
			</form>
			{% block links %}
			{% endblock %}
		{% endblock %}
	</body>
</html>

templates/source/html/index.html
{% extends 'source/html/base.html' %}

{% block title %}Paketübersicht {{ block.super }}{% endblock %}

{% block sub_content %}
{{ block.super }}
<h2>Was ist SOURCE?</h2>
<p>Source ist eine Webanwendung, die es ermöglicht Paketabhängigkeiten zwischen Quelltexten als 
Baum darszustellen sowie die Verwaltung von 
Quelltexten auf Meta-Ebene.</p>
{% endblock %}

{% block content %}
		<h2>Pakete</h2>
		<ul>
		{% for packet in packets %}
			<li><h3><a href="{{ packet.get_absolute_url }}">{{ packet }}</a></h3>
				{{ packet.description|truncatewords_html:40|safe }}
			<ul>
				{% for rep in packet.reps.all %}
				<li><p>{{ rep }}</p></li>
				{% endfor %}
			</ul>
			</li>
		{% endfor %}
		</ul>
{% endblock %}

templates/source/html/modul.html
{% extends 'source/html/base.html' %}

{% block title %}{{ modul }} {{ block.super }}{% endblock %}
{% block sub_content %}{{ block.super }}{% endblock %}
{% block links %}
			<h2>Menü</h2>
			<ul>
			{% if perms.source.change_modul %}
			<li><p><a href="{{ modul.get_admin_url }}">Eintrag <em>{{ modul }}</em> ändern</a></p></li>
			{% endif %}
			<li><p>{% if modul.get_previous_by_last_modified %}<a href="{{ modul.get_previous_by_last_modified.get_absolute_url }}">&laquo; {{ modul.get_previous_by_last_modified }}</a>{% endif %} | {% if modul.get_next_by_last_modified %}<a href="{{ modul.get_next_by_last_modified.get_absolute_url }}">&raquo; {{ modul.get_next_by_last_modified }}</a>{% endif %}</p></li>
			</ul>
{% endblock %}

{% block content %}
<h2>{{ modul }}</h2>
<table border="0">
    <tr>
        <th>
		    Name
        </th>
        <td><p><b>{{ modul }}</b></p><p>{{ modul.code_language }}</p></td>
        <td><p><a href="{{ modul.repository.get_absolute_url }}" title="Zeige Repository im Modulbaum">{{ modul.repository }}</a></p></td>
    </tr>
    <tr>
        <th>Version</th>
		<td colspan="2"><p>{{ modul.last_modified.date }} - Rev. {{ modul.revision }}</p></td>
    </tr>
    <tr>
        <th>Verweise</th>
        <td><p><b>Ruft auf</b></p>
		<ul>
			{% for a in modul.get_calls %}
			<li><p><a href="{{ a.get_absolute_url }}">{{ a }}</a></p>
				<ul>
					{% for b in a.get_calls %}
						<li><p><a href="{{ b.get_absolute_url }}">{{ b }}</a></p>
						<ul>
						{% for c in b.get_calls %}
							<li><p><a href="{{ c.get_absolute_url }}">{{ c }}</a></li></p>
						{% endfor %}
						</ul>
						</li>
					{% endfor %}
				</ul>
			</li>
			{% endfor %}
		</ul>
        </td>
        <td>
		<p><b>Wird aufgerufen von</b></p>
		<ul>
			{% for a in modul.get_called_by %}
			<li><p><a href="{{ a.get_absolute_url }}">{{ a }}</a></p>
				<ul>
					{% for b in a.get_called_by %}
						<li><p><a href="{{ b.get_absolute_url }}">{{ b }}</a></p>
						<ul>
						{% for c in b.get_called_by %}
							<li><p><a href="{{ c.get_absolute_url }}">{{ c }}</a></li></p>
						{% endfor %}
						</ul>
						</li>
					{% endfor %}
				</ul>
			</li>
			{% endfor %}
		</ul>
		</td>
    </tr>
    <tr>
        <th>Parameter</th>
        <td>
		<p><b>Input Parameter</b></p>
		<dl>
			{% for ip in modul.input_params.all %}
			<dt><p>{{ ip.key }}</p></dt>
				<dd><p>{{ ip.value }} [{{ ip.datatype }}]</p></dd>
			{% endfor %}
		</dl>
        </td>
        <td>
		<p><b>Output Parameter</b></p>
		<dl>
			{% for op in modul.output_params.all %}
			<dt><p>{{ op.key }}</p></dt>
				<dd><p>{{ op.value }} [{{ op.datatype }}]</p></dd>
			{% endfor %}
		</dl>
        </td>
    </tr>
    <tr>
        <th>Beschreibung</th>
        <td colspan="2">
		{{ modul.get_parsed_descr|safe }}
		</td>
    </tr>
</table>
{% endblock %}

templates/source/html/moduletree.html
{% extends 'source/html/base.html' %}

{% block sub_content %}
{{ block.super }}
<h2>Übersicht Pakete</h2>
<ul>
{% for packet in packets %}
<li><p><a href="#packet-{{ packet.slug }}">{{ packet }}</a></p>
	{% for rep in packet.reps.all %}
	<ul>
		<li><p><a href="#rep-{{ rep.slug }}">{{ rep }}</a></p></li>
	</ul>
	{% endfor %}
</li>
{% endfor %}
</ul>
{% endblock %}

{% block title %}Modulbaum {{ block.super }}{% endblock %}
{% block content %}
		<h2>Modulbaum</h2>
		<p>Der Modulbaum listet alle eigegeben Pakete und deren Repositories auf. Pro Repository werden alle Module mit ihren Abhängigkeiten Dargestellt. Die Tiefe der Abhängigkeiten ist auf maximal 3 Unterebenen beschränkt.</p>
		{% for packet in packets %}
		<h2><a name="packet-{{ packet.slug }}"></a>{{ packet }}</h2>
		{{ packet.description|safe }}
		<h3>Module</h3>
		<p><small>Auflistung aller Module (geordnet nach Repositories), die in der Datenbank vorhanden sind.</small></p>
		<ul>
			<p>{% for rep in packet.reps.all %}</p>
			<li><h4>Repository <a href="{{ rep.get_moduletree_url }}" name="rep-{{ rep.slug }}">{{ rep }}</a></h4>
				<ul>
				{% for mod in rep.modul_set.all %}
					<li class="modul">
						{% with mod.get_calls.count as total %}
						<p><a href="{{ mod.get_absolute_url }}">{{ mod }}</a></p>
						<table>
							<tr class="">
								<td colspan="{{ total }}"><p><small>{{ mod.code_description|striptags|truncatewords:20 }}</small></p></td>
							</tr>
							<tr class="even">
								{% for a_call in mod.get_calls|slice:":6" %}<th><p><a href="{{ a_call.get_absolute_url }}">{{ a_call }}</a></p></th>{% endfor %}
							</tr>
							<tr>
								{% for a_call in mod.get_calls|slice:":6" %}
								<td>
									<ul>
									{% for b_call in a_call.get_calls %}
										<li><p><a href="{{ b_call.get_absolute_url }}">{{ b_call }}</a></p>
										<ul>
										{% for c_call in b_call.get_calls %}
												<li><p><a href="{{ c_call.get_absolute_url }}">{{ c_call }}</a></p></li>
										{% endfor %}
										</ul>
										</li>
									{% endfor %}
									</ul>
								</td>
								{% endfor %}
							</tr>
						{% if total > 6 %}
							<tr class="even">
								{% for a_call in mod.get_calls|slice:"6:" %}<th><p><a href="{{ a_call.get_absolute_url }}">{{ a_call }}</a></p></th>{% endfor %}
							</tr>
							<tr>
								{% for a_call in mod.get_calls|slice:"6:" %}
								<td>
									<ul>
									{% for b_call in a_call.get_calls %}
										<li><p><a href="{{ b_call.get_absolute_url }}">{{ b_call }}</a></p>
										<ul>
										{% for c_call in b_call.get_calls %}
												<li><p><a href="{{ c_call.get_absolute_url }}">{{ c_call }}</a></p></li>
											{% endfor %}
										</ul>
										</li>
									{% endfor %}
									</ul>
								</td>
								{% endfor %}
							</tr>
						{% endif %}
						</table>
						{% endwith %}
					</li>
				{% endfor %}
				</ul>
			</li>
			{% endfor %}
		</ul>
		{% endfor %}
{% endblock %}

templates/source/html/package.html
{% extends 'source/html/base.html' %}

{% block title %}{{ block.super }}Paket {{ package }}{% endblock %}
{% block sub_content %}{{ block.super }}{% endblock %}
{% block content %}
		<h2>Paket {{ package }}</h2>
		{{ package.description|safe }}
		<h3>Repositories</h3>
		<ul>
			{% for rep in package.reps.all %}
			<li><p>{{ rep }}</p>
				<ul>
				{% for mod in rep.modul_set.all %}
					<li><p><b><a href="{{ mod.get_absolute_url }}">{{ mod }}</a></b></p>
					<ul>
					{% for a_call in mod.get_calls %}
						<li><p><a href="{{ a_call.get_absolute_url }}">{{ a_call }}</a></p>
						<ul>
							{% for b_call in a_call.get_calls %}
								<li><p><a href="{{ b_call.get_absolute_url }}">{{ b_call }}</a></p>
								<ul>
								{% for c_call in b_call.get_calls %}
										<li><p><a href="{{ c_call.get_absolute_url }}">{{ c_call }}</a></p></li>
									{% endfor %}
								</ul>
								</li>
							{% endfor %}
						</ul>
						</li>
					{% endfor %}
					</ul>
					</li>
				{% endfor %}
				</ul>
			</li>
			{% endfor %}
		</ul>
{% endblock %}

templates/source/html/search.html
{% extends 'source/html/base.html' %}

{% block title %}{{ block.super }}Suchergebnisse{% endblock %}

{% block sub_content %}
{{ block.super }}
<h2>Suchabschnitte</h2>
<ul>
	{% for model, res in results.items %}
	<li><p><a href="#{{ model }}">{{ model }}</a></p></li>
	{% endfor %}
</ul>
{% endblock %}

{% block content %}
		<h2>Suchergebnisse</h2>
		{% for model, res in results.items %}
			<a name="{{ model }}"></a>
			<h3>{{ model }}</h3>
			<ul>
				{% for r in res %}
					<li><p><a href="{{ r.get_absolute_url }}">{{ r }}</a></p></li>
				{% endfor %}
			</ul>
		{% endfor %}
{% endblock %}